# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='patient_no',
            field=models.BigIntegerField(default=0),
        ),
    ]
