# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20170108_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medreport',
            old_name='medno',
            new_name='medname',
        ),
    ]
