# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-13 19:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PHARMACY',
            fields=[
                ('ph_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ph_name', models.CharField(max_length=50)),
                ('ph_addr', models.CharField(default='Nil', max_length=100)),
                ('ph_phone', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
