# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedReport',
            fields=[
                ('med_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('medname', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=1000)),
                ('side_effect', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDB',
            fields=[
                ('p_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('p_image', models.ImageField(upload_to='')),
                ('p_name', models.CharField(max_length=50)),
                ('p_age', models.IntegerField()),
                ('p_sx', models.CharField(max_length=10)),
                ('p_addr', models.CharField(max_length=100)),
                ('p_NoK', models.CharField(default='Nil', max_length=50)),
                ('p_blood', models.CharField(max_length=3)),
                ('p_contact', models.CharField(max_length=50)),
                ('p_allerg', models.CharField(default='Nil', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='01/01/2017', max_length=10)),
                ('med', models.CharField(max_length=1000)),
                ('notes', models.CharField(max_length=1000)),
                ('doc', models.CharField(max_length=50)),
                ('patient_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.PatientDB')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set([('patient_no', 'date')]),
        ),
    ]
