# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doc_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('doc_image', models.ImageField(upload_to=b'images/doctors')),
                ('doc_name', models.CharField(max_length=50)),
                ('doc_sx', models.CharField(max_length=10)),
                ('doc_addr', models.CharField(max_length=100)),
                ('doc_phone', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedReport',
            fields=[
                ('med_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('medname', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=1000)),
                ('side_effect', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('p_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('p_image', models.ImageField(upload_to=b'images/patients')),
                ('p_name', models.CharField(max_length=50)),
                ('p_age', models.IntegerField()),
                ('p_sx', models.CharField(max_length=10)),
                ('p_addr', models.CharField(max_length=100)),
                ('p_NoK', models.CharField(default=b'Nil', max_length=50)),
                ('p_blood', models.CharField(max_length=3)),
                ('p_contact', models.CharField(max_length=50)),
                ('p_allerg', models.CharField(default=b'Nil', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Presciption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('per_day', models.IntegerField()),
                ('days', models.IntegerField()),
                ('pat_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('med', models.CharField(max_length=1000)),
                ('notes', models.CharField(max_length=1000)),
                ('doc', models.CharField(max_length=50)),
                ('patient_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Patient')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set([('patient_no', 'date')]),
        ),
    ]
