# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presciption',
            name='med_name',
        ),
        migrations.AddField(
            model_name='presciption',
            name='med_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctor.MedReport'),
            preserve_default=False,
        ),
    ]
