# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_report_patient_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='id',
        ),
        migrations.AlterField(
            model_name='report',
            name='patient_no',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
