# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20170211_0947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientDB',
            new_name='Patient',
        ),
    ]
