# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20170211_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doc_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('doc_image', models.ImageField(upload_to='')),
                ('doc_name', models.CharField(max_length=50)),
                ('doc_sx', models.CharField(max_length=10)),
                ('doc_addr', models.CharField(max_length=100)),
                ('doc_phone', models.BigIntegerField()),
                ('doc_pass', models.CharField(max_length=50)),
            ],
        ),
    ]
