# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20170108_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medreport',
            name='medname',
            field=models.CharField(max_length=50),
        ),
    ]
