# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_auto_20170108_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medreport',
            name='id',
        ),
        migrations.AddField(
            model_name='medreport',
            name='med_no',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
