# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20170108_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDB',
            fields=[
                ('p_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('p_image', models.ImageField(upload_to='')),
                ('p_name', models.CharField(max_length=50)),
                ('p_age', models.IntegerField()),
                ('p_sx', models.CharField(max_length=10)),
                ('p_addr', models.CharField(max_length=100)),
                ('p_NoK', models.CharField(default='Nil', max_length=50)),
                ('p_blood', models.CharField(max_length=3)),
                ('p_contact', models.CharField(max_length=50)),
                ('p_allerg', models.CharField(default='Nil', max_length=100)),
            ],
        ),
    ]
